# Generated by Django 2.2.1 on 2019-06-15 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_remove_article_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(default='', upload_to='articles/images'),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
